spring:
  application:
    name: config-server # 应用名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uniwjj/eureka-demo # 配置git仓库的地址
          search-paths: config-repo  # git仓库地址下的相对地址，可以配置多个，用“,”分割。

server:
  port: 9004 # 服务端口
#  servlet:
#    context-path: /config-server

# 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ # 注册中心地址

